FROM fedora:25

MAINTAINER "Petr Hracek" <phracek@redhat.com>

RUN dnf install -y --setopt=tsflags=nodocs \
    abrt \
    ethtool \
    iproute \
    iputils \
    ltrace \
    mailx \
    net-tools \
    netsniff-ng \
    nmap-ncat \
    strace \
    sysstat \
    tcpdump \
    xorg-x11-xauth && \
    dnf -y clean all

CMD ["/usr/bin/bash"]
